import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "./(Compounts)/UI/(navbar)/Navbar";
import { SelectionProvider } from "./(Compounts)/Context/SelectionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "WildfireMap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="w-full h-screen overflow-hidden">
        <SelectionProvider>
          <Navbar />
          {children}
        </SelectionProvider>

        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
